name: utility_extensions
description: This package will help you to reduce your code for many things.
version: 0.0.9
homepage: https://github.com/hamzali4642/utility_extensions

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:


